version: '3.7'
services:
  web:
    image: nginx:1.17-alpine
    container_name: web
    restart: unless-stopped
    ports:
      - '${APP_PORT}:80'
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - streamingnet

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - database
    networks:
      - streamingnet
    #Database Service
  database:
    image: mysql
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - ./db/:/var/lib/mysql
    healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    networks:
        - streamingnet
  phpmyadmin:
        image: phpmyadmin
        restart: always
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - '${DB_ADM_FORWARD_PORT:-8080}:80'
        depends_on:
            -   database
        networks:
            - streamingnet
networks:
  streamingnet:
    driver: bridge